name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy 1.18.5
  - psutil 5.7.0
  - toolz 0.10.0
  - matplotlib 3.2.2
  - pandas 1.0.5
  - partd 1.1.0
  - bokeh 2.1.1
  - dask 2.20.0
